kind: Service
apiVersion: v1
metadata:
  name: {{.Values.service.name}} 
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-ssl-cert: {{.Values.service.certificateAwsArn}}
    service.beta.kubernetes.io/aws-load-balancer-ssl-ports: "443"
    service.beta.kubernetes.io/aws-load-balancer-backend-protocol: http
    service.beta.kubernetes.io/aws-load-balancer-additional-resource-tags: "{{ .Values.elb.tags }}"
    {{- if eq .Values.s3.enabled "true" }}
    service.beta.kubernetes.io/aws-load-balancer-access-log-enabled: "{{ .Values.s3.enabled }}"
    service.beta.kubernetes.io/aws-load-balancer-access-log-s3-bucket-name: "{{ .Values.s3.bucketName }}"
    service.beta.kubernetes.io/aws-load-balancer-access-log-s3-bucket-prefix: "{{ .Values.s3.prefix }}"
    service.beta.kubernetes.io/aws-load-balancer-access-log-emit-interval: "{{ .Values.s3.interval }}"
    {{- end }}
    
  labels:
    chart: "{{ .Chart.Name | trunc 63 }}"
    chartVersion: "{{ .Chart.Version | trunc 63 }}"
    app: {{.Values.service.name}}
    visualize: "true" 
spec:
  type: LoadBalancer
  ports: 
    - port: 443
#      name: # The name of this port within the service. Optional if only one port is defined on this service
      targetPort: 80
  selector: 
    app: {{ .Values.service.name }} 
